var hierarchy =
[
    [ "FMOD._3D_ATTRIBUTES", "struct_f_m_o_d_1_1__3_d___a_t_t_r_i_b_u_t_e_s.html", null ],
    [ "FMOD.ADVANCEDSETTINGS", "struct_f_m_o_d_1_1_a_d_v_a_n_c_e_d_s_e_t_t_i_n_g_s.html", null ],
    [ "Othello::UI::Main::Allegro", "class_othello_1_1_u_i_1_1_main_1_1_allegro.html", null ],
    [ "Othello::UI::Games::AllegroValidMoveTreeViewer", "class_othello_1_1_u_i_1_1_games_1_1_allegro_valid_move_tree_viewer.html", null ],
    [ "Othello::Algorithms::AlphaBeta", "class_othello_1_1_algorithms_1_1_alpha_beta.html", null ],
    [ "Othello::UI::Main::AnimatedRectangle", "class_othello_1_1_u_i_1_1_main_1_1_animated_rectangle.html", [
      [ "Othello::UI::Main::ButtonRectangle", "class_othello_1_1_u_i_1_1_main_1_1_button_rectangle.html", null ],
      [ "Othello::UI::Main::MenuRectangle", "class_othello_1_1_u_i_1_1_main_1_1_menu_rectangle.html", null ]
    ] ],
    [ "FMOD.ASYNCREADINFO", "struct_f_m_o_d_1_1_a_s_y_n_c_r_e_a_d_i_n_f_o.html", null ],
    [ "FMOD.CHANNELCONTROL_DSP_INDEX", "struct_f_m_o_d_1_1_c_h_a_n_n_e_l_c_o_n_t_r_o_l___d_s_p___i_n_d_e_x.html", null ],
    [ "Othello::UI::Main::CLI", "class_othello_1_1_u_i_1_1_main_1_1_c_l_i.html", null ],
    [ "Functions::CLI", "class_functions_1_1_c_l_i.html", null ],
    [ "Othello::UI::Games::CLIValidMoveTreeViewer", "class_othello_1_1_u_i_1_1_games_1_1_c_l_i_valid_move_tree_viewer.html", null ],
    [ "FMOD.COMPLEX", "struct_f_m_o_d_1_1_c_o_m_p_l_e_x.html", null ],
    [ "FMOD.CONSTANTS", "class_f_m_o_d_1_1_c_o_n_s_t_a_n_t_s.html", null ],
    [ "FMOD.CREATESOUNDEXINFO", "struct_f_m_o_d_1_1_c_r_e_a_t_e_s_o_u_n_d_e_x_i_n_f_o.html", null ],
    [ "FMOD.Debug", "class_f_m_o_d_1_1_debug.html", null ],
    [ "Othello::Board::DirectionVector", "struct_othello_1_1_board_1_1_direction_vector.html", null ],
    [ "FMOD.DSP_BUFFER_ARRAY", "struct_f_m_o_d_1_1_d_s_p___b_u_f_f_e_r___a_r_r_a_y.html", null ],
    [ "FMOD.DSP_DESCRIPTION", "struct_f_m_o_d_1_1_d_s_p___d_e_s_c_r_i_p_t_i_o_n.html", null ],
    [ "FMOD.DSP_METERING_INFO", "class_f_m_o_d_1_1_d_s_p___m_e_t_e_r_i_n_g___i_n_f_o.html", null ],
    [ "FMOD.DSP_PARAMETER_3DATTRIBUTES", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r__3_d_a_t_t_r_i_b_u_t_e_s.html", null ],
    [ "FMOD.DSP_PARAMETER_3DATTRIBUTES_MULTI", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r__3_d_a_t_t_r_i_b_u_t_e_s___m_u_l_t_i.html", null ],
    [ "FMOD.DSP_PARAMETER_DESC", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c.html", null ],
    [ "FMOD.DSP_PARAMETER_DESC_BOOL", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___b_o_o_l.html", null ],
    [ "FMOD.DSP_PARAMETER_DESC_DATA", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___d_a_t_a.html", null ],
    [ "FMOD.DSP_PARAMETER_DESC_FLOAT", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___f_l_o_a_t.html", null ],
    [ "FMOD.DSP_PARAMETER_DESC_INT", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___i_n_t.html", null ],
    [ "FMOD.DSP_PARAMETER_DESC_UNION", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___u_n_i_o_n.html", null ],
    [ "FMOD.DSP_PARAMETER_FFT", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___f_f_t.html", null ],
    [ "FMOD.DSP_PARAMETER_FLOAT_MAPPING", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___f_l_o_a_t___m_a_p_p_i_n_g.html", null ],
    [ "FMOD.DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___f_l_o_a_t___m_a_p_p_i_n_g___p_i_e_c_e_w_i_s_e___l_i_n_e_a_r.html", null ],
    [ "FMOD.DSP_PARAMETER_OVERALLGAIN", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___o_v_e_r_a_l_l_g_a_i_n.html", null ],
    [ "FMOD.DSP_PARAMETER_SIDECHAIN", "struct_f_m_o_d_1_1_d_s_p___p_a_r_a_m_e_t_e_r___s_i_d_e_c_h_a_i_n.html", null ],
    [ "FMOD.DSP_STATE", "struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e.html", null ],
    [ "FMOD.DSP_STATE_DFTCALLBACKS", "struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e___d_f_t_c_a_l_l_b_a_c_k_s.html", null ],
    [ "FMOD.DSP_STATE_PAN_CALLBACKS", "struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e___p_a_n___c_a_l_l_b_a_c_k_s.html", null ],
    [ "FMOD.DSP_STATE_SYSTEMCALLBACKS", "struct_f_m_o_d_1_1_d_s_p___s_t_a_t_e___s_y_s_t_e_m_c_a_l_l_b_a_c_k_s.html", null ],
    [ "FMOD.Error", "class_f_m_o_d_1_1_error.html", null ],
    [ "FMOD.ERRORCALLBACK_INFO", "struct_f_m_o_d_1_1_e_r_r_o_r_c_a_l_l_b_a_c_k___i_n_f_o.html", null ],
    [ "exception", null, [
      [ "Othello::exceptions::exit_game", "class_othello_1_1exceptions_1_1exit__game.html", null ],
      [ "Othello::exceptions::invalid_save", "class_othello_1_1exceptions_1_1invalid__save.html", null ],
      [ "Othello::exceptions::no_selected_move", "class_othello_1_1exceptions_1_1no__selected__move.html", null ]
    ] ],
    [ "FMOD.Factory", "class_f_m_o_d_1_1_factory.html", null ],
    [ "Othello::UI::Audio::FMOD", "class_othello_1_1_u_i_1_1_audio_1_1_f_m_o_d.html", null ],
    [ "FMOD_3D_ATTRIBUTES", "struct_f_m_o_d__3_d___a_t_t_r_i_b_u_t_e_s.html", null ],
    [ "FMOD_ADVANCEDSETTINGS", "struct_f_m_o_d___a_d_v_a_n_c_e_d_s_e_t_t_i_n_g_s.html", null ],
    [ "FMOD_ASYNCREADINFO", "struct_f_m_o_d___a_s_y_n_c_r_e_a_d_i_n_f_o.html", null ],
    [ "FMOD_CODEC_DESCRIPTION", "struct_f_m_o_d___c_o_d_e_c___d_e_s_c_r_i_p_t_i_o_n.html", null ],
    [ "FMOD_CODEC_STATE", "struct_f_m_o_d___c_o_d_e_c___s_t_a_t_e.html", null ],
    [ "FMOD_CODEC_WAVEFORMAT", "struct_f_m_o_d___c_o_d_e_c___w_a_v_e_f_o_r_m_a_t.html", null ],
    [ "FMOD_COMPLEX", "struct_f_m_o_d___c_o_m_p_l_e_x.html", null ],
    [ "FMOD_CREATESOUNDEXINFO", "struct_f_m_o_d___c_r_e_a_t_e_s_o_u_n_d_e_x_i_n_f_o.html", null ],
    [ "FMOD_DSP_BUFFER_ARRAY", "struct_f_m_o_d___d_s_p___b_u_f_f_e_r___a_r_r_a_y.html", null ],
    [ "FMOD_DSP_DESCRIPTION", "struct_f_m_o_d___d_s_p___d_e_s_c_r_i_p_t_i_o_n.html", null ],
    [ "FMOD_DSP_METERING_INFO", "struct_f_m_o_d___d_s_p___m_e_t_e_r_i_n_g___i_n_f_o.html", null ],
    [ "FMOD_DSP_PARAMETER_3DATTRIBUTES", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r__3_d_a_t_t_r_i_b_u_t_e_s.html", null ],
    [ "FMOD_DSP_PARAMETER_3DATTRIBUTES_MULTI", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r__3_d_a_t_t_r_i_b_u_t_e_s___m_u_l_t_i.html", null ],
    [ "FMOD_DSP_PARAMETER_DESC", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c.html", null ],
    [ "FMOD_DSP_PARAMETER_DESC_BOOL", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___b_o_o_l.html", null ],
    [ "FMOD_DSP_PARAMETER_DESC_DATA", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___d_a_t_a.html", null ],
    [ "FMOD_DSP_PARAMETER_DESC_FLOAT", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___f_l_o_a_t.html", null ],
    [ "FMOD_DSP_PARAMETER_DESC_INT", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___d_e_s_c___i_n_t.html", null ],
    [ "FMOD_DSP_PARAMETER_FFT", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___f_f_t.html", null ],
    [ "FMOD_DSP_PARAMETER_FLOAT_MAPPING", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___f_l_o_a_t___m_a_p_p_i_n_g.html", null ],
    [ "FMOD_DSP_PARAMETER_FLOAT_MAPPING_PIECEWISE_LINEAR", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___f_l_o_a_t___m_a_p_p_i_n_g___p_i_e_c_e_w_i_s_e___l_i_n_e_a_r.html", null ],
    [ "FMOD_DSP_PARAMETER_OVERALLGAIN", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___o_v_e_r_a_l_l_g_a_i_n.html", null ],
    [ "FMOD_DSP_PARAMETER_SIDECHAIN", "struct_f_m_o_d___d_s_p___p_a_r_a_m_e_t_e_r___s_i_d_e_c_h_a_i_n.html", null ],
    [ "FMOD_DSP_STATE", "struct_f_m_o_d___d_s_p___s_t_a_t_e.html", null ],
    [ "FMOD_DSP_STATE_DFTCALLBACKS", "struct_f_m_o_d___d_s_p___s_t_a_t_e___d_f_t_c_a_l_l_b_a_c_k_s.html", null ],
    [ "FMOD_DSP_STATE_PAN_CALLBACKS", "struct_f_m_o_d___d_s_p___s_t_a_t_e___p_a_n___c_a_l_l_b_a_c_k_s.html", null ],
    [ "FMOD_DSP_STATE_SYSTEMCALLBACKS", "struct_f_m_o_d___d_s_p___s_t_a_t_e___s_y_s_t_e_m_c_a_l_l_b_a_c_k_s.html", null ],
    [ "FMOD_ERRORCALLBACK_INFO", "struct_f_m_o_d___e_r_r_o_r_c_a_l_l_b_a_c_k___i_n_f_o.html", null ],
    [ "FMOD_GUID", "struct_f_m_o_d___g_u_i_d.html", null ],
    [ "FMOD_OUTPUT_DESCRIPTION", "struct_f_m_o_d___o_u_t_p_u_t___d_e_s_c_r_i_p_t_i_o_n.html", null ],
    [ "FMOD_OUTPUT_STATE", "struct_f_m_o_d___o_u_t_p_u_t___s_t_a_t_e.html", null ],
    [ "FMOD_REVERB_PROPERTIES", "struct_f_m_o_d___r_e_v_e_r_b___p_r_o_p_e_r_t_i_e_s.html", null ],
    [ "FMOD_TAG", "struct_f_m_o_d___t_a_g.html", null ],
    [ "FMOD_VECTOR", "struct_f_m_o_d___v_e_c_t_o_r.html", null ],
    [ "Othello::Game", "class_othello_1_1_game.html", null ],
    [ "Othello::UI::Game", "class_othello_1_1_u_i_1_1_game.html", [
      [ "Othello::UI::Games::Allegro", "class_othello_1_1_u_i_1_1_games_1_1_allegro.html", null ],
      [ "Othello::UI::Games::CLI", "class_othello_1_1_u_i_1_1_games_1_1_c_l_i.html", null ]
    ] ],
    [ "Othello::Board::GameBoard", "class_othello_1_1_board_1_1_game_board.html", null ],
    [ "ImFont::Glyph", "struct_im_font_1_1_glyph.html", null ],
    [ "FMOD.HandleBase", "class_f_m_o_d_1_1_handle_base.html", [
      [ "FMOD.ChannelControl", "class_f_m_o_d_1_1_channel_control.html", [
        [ "FMOD.Channel", "class_f_m_o_d_1_1_channel.html", null ],
        [ "FMOD.Channel", "class_f_m_o_d_1_1_channel.html", null ],
        [ "FMOD.ChannelGroup", "class_f_m_o_d_1_1_channel_group.html", null ],
        [ "FMOD.ChannelGroup", "class_f_m_o_d_1_1_channel_group.html", null ]
      ] ],
      [ "FMOD.DSP", "class_f_m_o_d_1_1_d_s_p.html", null ],
      [ "FMOD.DSPConnection", "class_f_m_o_d_1_1_d_s_p_connection.html", null ],
      [ "FMOD.Geometry", "class_f_m_o_d_1_1_geometry.html", null ],
      [ "FMOD.Reverb3D", "class_f_m_o_d_1_1_reverb3_d.html", null ],
      [ "FMOD.Sound", "class_f_m_o_d_1_1_sound.html", null ],
      [ "FMOD.SoundGroup", "class_f_m_o_d_1_1_sound_group.html", null ],
      [ "FMOD.System", "class_f_m_o_d_1_1_system.html", null ]
    ] ],
    [ "Othello::Algorithms::Heuristics", "class_othello_1_1_algorithms_1_1_heuristics.html", null ],
    [ "ImColor", "struct_im_color.html", null ],
    [ "ImDrawChannel", "struct_im_draw_channel.html", null ],
    [ "ImDrawCmd", "struct_im_draw_cmd.html", null ],
    [ "ImDrawData", "struct_im_draw_data.html", null ],
    [ "ImDrawList", "struct_im_draw_list.html", null ],
    [ "ImDrawVert", "struct_im_draw_vert.html", null ],
    [ "ImFont", "struct_im_font.html", null ],
    [ "ImFontAtlas", "struct_im_font_atlas.html", null ],
    [ "ImFontConfig", "struct_im_font_config.html", null ],
    [ "ImGuiColMod", "struct_im_gui_col_mod.html", null ],
    [ "ImGuiColumnData", "struct_im_gui_column_data.html", null ],
    [ "ImGuiContext", "struct_im_gui_context.html", null ],
    [ "ImGuiDrawContext", "struct_im_gui_draw_context.html", null ],
    [ "ImGuiGroupData", "struct_im_gui_group_data.html", null ],
    [ "ImGuiIniData", "struct_im_gui_ini_data.html", null ],
    [ "ImGuiIO", "struct_im_gui_i_o.html", null ],
    [ "ImGuiListClipper", "struct_im_gui_list_clipper.html", null ],
    [ "ImGuiMouseCursorData", "struct_im_gui_mouse_cursor_data.html", null ],
    [ "ImGuiOnceUponAFrame", "struct_im_gui_once_upon_a_frame.html", null ],
    [ "ImGuiPlotArrayGetterData", "struct_im_gui_plot_array_getter_data.html", null ],
    [ "ImGuiPopupRef", "struct_im_gui_popup_ref.html", null ],
    [ "ImGuiSimpleColumns", "struct_im_gui_simple_columns.html", null ],
    [ "ImGuiSizeConstraintCallbackData", "struct_im_gui_size_constraint_callback_data.html", null ],
    [ "ImGuiStorage", "struct_im_gui_storage.html", null ],
    [ "ImGuiStyle", "struct_im_gui_style.html", null ],
    [ "ImGuiStyleMod", "struct_im_gui_style_mod.html", null ],
    [ "ImGuiStyleVarInfo", "struct_im_gui_style_var_info.html", null ],
    [ "ImGuiTextBuffer", "struct_im_gui_text_buffer.html", null ],
    [ "ImGuiTextEditCallbackData", "struct_im_gui_text_edit_callback_data.html", null ],
    [ "ImGuiTextEditState", "struct_im_gui_text_edit_state.html", null ],
    [ "ImGuiTextFilter", "struct_im_gui_text_filter.html", null ],
    [ "ImGuiWindow", "struct_im_gui_window.html", null ],
    [ "ImRect", "struct_im_rect.html", null ],
    [ "ImVec2", "struct_im_vec2.html", null ],
    [ "ImVec4", "struct_im_vec4.html", null ],
    [ "ImVector< T >", "class_im_vector.html", null ],
    [ "ImVector< bool >", "class_im_vector.html", null ],
    [ "ImVector< char >", "class_im_vector.html", null ],
    [ "ImVector< float >", "class_im_vector.html", null ],
    [ "ImVector< ImDrawChannel >", "class_im_vector.html", null ],
    [ "ImVector< ImDrawCmd >", "class_im_vector.html", null ],
    [ "ImVector< ImDrawIdx >", "class_im_vector.html", null ],
    [ "ImVector< ImDrawList *>", "class_im_vector.html", null ],
    [ "ImVector< ImDrawVert >", "class_im_vector.html", null ],
    [ "ImVector< ImFont *>", "class_im_vector.html", null ],
    [ "ImVector< ImFont::Glyph >", "class_im_vector.html", null ],
    [ "ImVector< ImFontConfig >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiColMod >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiColumnData >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiGroupData >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiID >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiIniData >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiPopupRef >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiStorage::Pair >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiStyleMod >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiTextFilter::TextRange >", "class_im_vector.html", null ],
    [ "ImVector< ImGuiWindow *>", "class_im_vector.html", null ],
    [ "ImVector< ImTextureID >", "class_im_vector.html", null ],
    [ "ImVector< ImVec2 >", "class_im_vector.html", null ],
    [ "ImVector< ImVec4 >", "class_im_vector.html", null ],
    [ "ImVector< ImWchar >", "class_im_vector.html", null ],
    [ "ImVector< unsigned short >", "class_im_vector.html", null ],
    [ "logic_error", null, [
      [ "Othello::exceptions::invalid_move", "class_othello_1_1exceptions_1_1invalid__move.html", null ]
    ] ],
    [ "FMOD.Memory", "class_f_m_o_d_1_1_memory.html", null ],
    [ "menu", "classmenu.html", null ],
    [ "Functions::CLIs::Menu", "class_functions_1_1_c_l_is_1_1_menu.html", null ],
    [ "Othello::UI::Games::MessageBar", "class_othello_1_1_u_i_1_1_games_1_1_message_bar.html", [
      [ "Othello::UI::Games::ErrorBar", "class_othello_1_1_u_i_1_1_games_1_1_error_bar.html", null ]
    ] ],
    [ "Othello::Algorithms::MiniMax", "class_othello_1_1_algorithms_1_1_mini_max.html", null ],
    [ "Othello::Board::Move", "struct_othello_1_1_board_1_1_move.html", [
      [ "Othello::Board::ValidMove", "struct_othello_1_1_board_1_1_valid_move.html", null ]
    ] ],
    [ "ImGuiStorage::Pair", "struct_im_gui_storage_1_1_pair.html", null ],
    [ "Othello::Players::Player", "class_othello_1_1_players_1_1_player.html", [
      [ "Othello::Players::UIPlayer", "class_othello_1_1_players_1_1_u_i_player.html", [
        [ "Othello::Players::EnhancedAI", "class_othello_1_1_players_1_1_enhanced_a_i.html", null ],
        [ "Othello::Players::Human", "class_othello_1_1_players_1_1_human.html", null ],
        [ "Othello::Players::RandomAI", "class_othello_1_1_players_1_1_random_a_i.html", null ],
        [ "Othello::Players::SimpleAI", "class_othello_1_1_players_1_1_simple_a_i.html", null ]
      ] ]
    ] ],
    [ "FMOD.PORT_INDEX", "struct_f_m_o_d_1_1_p_o_r_t___i_n_d_e_x.html", null ],
    [ "FMOD.PRESET", "class_f_m_o_d_1_1_p_r_e_s_e_t.html", null ],
    [ "Othello::Board::Pun", "struct_othello_1_1_board_1_1_pun.html", null ],
    [ "Othello::Board::PunCount", "struct_othello_1_1_board_1_1_pun_count.html", null ],
    [ "FMOD.REVERB_PROPERTIES", "struct_f_m_o_d_1_1_r_e_v_e_r_b___p_r_o_p_e_r_t_i_e_s.html", null ],
    [ "Othello::Save::Save", "struct_othello_1_1_save_1_1_save.html", null ],
    [ "Othello::Save::SaveManager", "class_othello_1_1_save_1_1_save_manager.html", null ],
    [ "STB_TexteditState", "struct_s_t_b___textedit_state.html", null ],
    [ "ImGuiStb::STB_TexteditState", "struct_im_gui_stb_1_1_s_t_b___textedit_state.html", null ],
    [ "ImGuiStb::StbFindState", "struct_im_gui_stb_1_1_stb_find_state.html", null ],
    [ "stbrp_context", "structstbrp__context.html", null ],
    [ "stbrp_node", "structstbrp__node.html", null ],
    [ "stbrp_rect", "structstbrp__rect.html", null ],
    [ "ImGuiStb::StbTexteditRow", "struct_im_gui_stb_1_1_stb_textedit_row.html", null ],
    [ "StbTexteditRow", "struct_stb_textedit_row.html", null ],
    [ "stbtt__bitmap", "structstbtt____bitmap.html", null ],
    [ "stbtt__buf", "structstbtt____buf.html", null ],
    [ "stbtt_aligned_quad", "structstbtt__aligned__quad.html", null ],
    [ "stbtt_bakedchar", "structstbtt__bakedchar.html", null ],
    [ "stbtt_fontinfo", "structstbtt__fontinfo.html", null ],
    [ "stbtt_pack_context", "structstbtt__pack__context.html", null ],
    [ "stbtt_pack_range", "structstbtt__pack__range.html", null ],
    [ "stbtt_packedchar", "structstbtt__packedchar.html", null ],
    [ "stbtt_vertex", "structstbtt__vertex.html", null ],
    [ "ImGuiStb::StbUndoRecord", "struct_im_gui_stb_1_1_stb_undo_record.html", null ],
    [ "StbUndoRecord", "struct_stb_undo_record.html", null ],
    [ "ImGuiStb::StbUndoState", "struct_im_gui_stb_1_1_stb_undo_state.html", null ],
    [ "StbUndoState", "struct_stb_undo_state.html", null ],
    [ "FMOD.StringMarshalHelper", "class_f_m_o_d_1_1_string_marshal_helper.html", null ],
    [ "FMOD.StringWrapper", "struct_f_m_o_d_1_1_string_wrapper.html", null ],
    [ "FMOD.TAG", "struct_f_m_o_d_1_1_t_a_g.html", null ],
    [ "ImGuiTextFilter::TextRange", "struct_im_gui_text_filter_1_1_text_range.html", null ],
    [ "Othello::Board::Tree::ValidMoveNode", "class_othello_1_1_board_1_1_tree_1_1_valid_move_node.html", null ],
    [ "FMOD.VECTOR", "struct_f_m_o_d_1_1_v_e_c_t_o_r.html", null ],
    [ "FMOD.VERSION", "class_f_m_o_d_1_1_v_e_r_s_i_o_n.html", null ]
];