var searchData=
[
  ['imcolor',['ImColor',['../struct_im_color.html',1,'']]],
  ['imdrawchannel',['ImDrawChannel',['../struct_im_draw_channel.html',1,'']]],
  ['imdrawcmd',['ImDrawCmd',['../struct_im_draw_cmd.html',1,'']]],
  ['imdrawdata',['ImDrawData',['../struct_im_draw_data.html',1,'']]],
  ['imdrawlist',['ImDrawList',['../struct_im_draw_list.html',1,'']]],
  ['imdrawvert',['ImDrawVert',['../struct_im_draw_vert.html',1,'']]],
  ['imfont',['ImFont',['../struct_im_font.html',1,'']]],
  ['imfontatlas',['ImFontAtlas',['../struct_im_font_atlas.html',1,'']]],
  ['imfontconfig',['ImFontConfig',['../struct_im_font_config.html',1,'']]],
  ['imguicolmod',['ImGuiColMod',['../struct_im_gui_col_mod.html',1,'']]],
  ['imguicolumndata',['ImGuiColumnData',['../struct_im_gui_column_data.html',1,'']]],
  ['imguicontext',['ImGuiContext',['../struct_im_gui_context.html',1,'']]],
  ['imguidrawcontext',['ImGuiDrawContext',['../struct_im_gui_draw_context.html',1,'']]],
  ['imguigroupdata',['ImGuiGroupData',['../struct_im_gui_group_data.html',1,'']]],
  ['imguiinidata',['ImGuiIniData',['../struct_im_gui_ini_data.html',1,'']]],
  ['imguiio',['ImGuiIO',['../struct_im_gui_i_o.html',1,'']]],
  ['imguilistclipper',['ImGuiListClipper',['../struct_im_gui_list_clipper.html',1,'']]],
  ['imguimousecursordata',['ImGuiMouseCursorData',['../struct_im_gui_mouse_cursor_data.html',1,'']]],
  ['imguionceuponaframe',['ImGuiOnceUponAFrame',['../struct_im_gui_once_upon_a_frame.html',1,'']]],
  ['imguiplotarraygetterdata',['ImGuiPlotArrayGetterData',['../struct_im_gui_plot_array_getter_data.html',1,'']]],
  ['imguipopupref',['ImGuiPopupRef',['../struct_im_gui_popup_ref.html',1,'']]],
  ['imguisimplecolumns',['ImGuiSimpleColumns',['../struct_im_gui_simple_columns.html',1,'']]],
  ['imguisizeconstraintcallbackdata',['ImGuiSizeConstraintCallbackData',['../struct_im_gui_size_constraint_callback_data.html',1,'']]],
  ['imguistorage',['ImGuiStorage',['../struct_im_gui_storage.html',1,'']]],
  ['imguistyle',['ImGuiStyle',['../struct_im_gui_style.html',1,'']]],
  ['imguistylemod',['ImGuiStyleMod',['../struct_im_gui_style_mod.html',1,'']]],
  ['imguistylevarinfo',['ImGuiStyleVarInfo',['../struct_im_gui_style_var_info.html',1,'']]],
  ['imguitextbuffer',['ImGuiTextBuffer',['../struct_im_gui_text_buffer.html',1,'']]],
  ['imguitexteditcallbackdata',['ImGuiTextEditCallbackData',['../struct_im_gui_text_edit_callback_data.html',1,'']]],
  ['imguitexteditstate',['ImGuiTextEditState',['../struct_im_gui_text_edit_state.html',1,'']]],
  ['imguitextfilter',['ImGuiTextFilter',['../struct_im_gui_text_filter.html',1,'']]],
  ['imguiwindow',['ImGuiWindow',['../struct_im_gui_window.html',1,'']]],
  ['imrect',['ImRect',['../struct_im_rect.html',1,'']]],
  ['imvec2',['ImVec2',['../struct_im_vec2.html',1,'']]],
  ['imvec4',['ImVec4',['../struct_im_vec4.html',1,'']]],
  ['imvector',['ImVector',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20bool_20_3e',['ImVector&lt; bool &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20char_20_3e',['ImVector&lt; char &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20float_20_3e',['ImVector&lt; float &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawchannel_20_3e',['ImVector&lt; ImDrawChannel &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawcmd_20_3e',['ImVector&lt; ImDrawCmd &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawidx_20_3e',['ImVector&lt; ImDrawIdx &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawlist_20_2a_3e',['ImVector&lt; ImDrawList *&gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imdrawvert_20_3e',['ImVector&lt; ImDrawVert &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imfont_20_2a_3e',['ImVector&lt; ImFont *&gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imfont_3a_3aglyph_20_3e',['ImVector&lt; ImFont::Glyph &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imfontconfig_20_3e',['ImVector&lt; ImFontConfig &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguicolmod_20_3e',['ImVector&lt; ImGuiColMod &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguicolumndata_20_3e',['ImVector&lt; ImGuiColumnData &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguigroupdata_20_3e',['ImVector&lt; ImGuiGroupData &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguiid_20_3e',['ImVector&lt; ImGuiID &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguiinidata_20_3e',['ImVector&lt; ImGuiIniData &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguipopupref_20_3e',['ImVector&lt; ImGuiPopupRef &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguistorage_3a_3apair_20_3e',['ImVector&lt; ImGuiStorage::Pair &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguistylemod_20_3e',['ImVector&lt; ImGuiStyleMod &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguitextfilter_3a_3atextrange_20_3e',['ImVector&lt; ImGuiTextFilter::TextRange &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imguiwindow_20_2a_3e',['ImVector&lt; ImGuiWindow *&gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imtextureid_20_3e',['ImVector&lt; ImTextureID &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imvec2_20_3e',['ImVector&lt; ImVec2 &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imvec4_20_3e',['ImVector&lt; ImVec4 &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20imwchar_20_3e',['ImVector&lt; ImWchar &gt;',['../class_im_vector.html',1,'']]],
  ['imvector_3c_20unsigned_20short_20_3e',['ImVector&lt; unsigned short &gt;',['../class_im_vector.html',1,'']]],
  ['inform',['inform',['../class_othello_1_1_u_i_1_1_games_1_1_allegro.html#a14ef81d6470102f7f02bec00c0b604ad',1,'Othello::UI::Games::Allegro::inform()'],['../class_othello_1_1_u_i_1_1_games_1_1_c_l_i.html#a09cb1d9af2d217fe1a59853160d7dad2',1,'Othello::UI::Games::CLI::inform()'],['../class_othello_1_1_u_i_1_1_game.html#a3b033a0cc4c900847ce6f90643ee856c',1,'Othello::UI::Game::inform()']]],
  ['informnoavailablemoves',['informNoAvailableMoves',['../class_othello_1_1_u_i_1_1_games_1_1_allegro.html#a81212f548827c719d8de0531a212276a',1,'Othello::UI::Games::Allegro::informNoAvailableMoves()'],['../class_othello_1_1_u_i_1_1_games_1_1_c_l_i.html#a164755bcff396872544282c1b3aa15a6',1,'Othello::UI::Games::CLI::informNoAvailableMoves()'],['../class_othello_1_1_u_i_1_1_game.html#a1501de4551a95aa863338372c9cbba27',1,'Othello::UI::Game::informNoAvailableMoves()']]],
  ['invalid_5fmove',['invalid_move',['../class_othello_1_1exceptions_1_1invalid__move.html',1,'Othello::exceptions::invalid_move'],['../class_othello_1_1exceptions_1_1invalid__move.html#a48b36c3ae4d8b05e7f3bea5d67d72bbe',1,'Othello::exceptions::invalid_move::invalid_move(const std::string &amp;what_arg)'],['../class_othello_1_1exceptions_1_1invalid__move.html#ae5d7c0f4942a02611fc14dd6a10b5689',1,'Othello::exceptions::invalid_move::invalid_move(const char *what_arg)']]],
  ['invalid_5fsave',['invalid_save',['../class_othello_1_1exceptions_1_1invalid__save.html',1,'Othello::exceptions']]],
  ['issue',['issue',['../class_othello_1_1_board_1_1_game_board.html#a8dadb4f88e01f70db150d6f3128ea7ea',1,'Othello::Board::GameBoard']]]
];
